environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python37"

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

  - python -m pip --version
  # - python -m pip install --disable-pip-version-check --user --upgrade pip

  - pip install -r dev-requirements.txt
  - pip install wheel
  - pip install pypiwin32
  - pip install -e .

build: false

test_script:
  - python setup.py test -c

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: .coverage
    name: Coverage

  - path: dist\*
    name: Wheels
