language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

install: 
    - pip install six
    - pip install paramiko

before_script:
    - "echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config"
    - "echo StrictHostKeyChecking no >> ~/.ssh/config"
    - "ssh-keygen -q -f ~/.ssh/id_rsa -N ''"
    - "cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys"
    - "python setup.py install"
    - "cd tests"

script: nosetests -vv -d

notifications:
    email:
        on_success: change
        on_failure: change
